# An example conf.toml, just for reference.
# Usually you don't need to make one yourself, you can
# modify your `Conf` object however you want and then
# write it out.  But sometimes it's useful to know
# which options there are.

[window_mode]
width = 800
height = 600
maximized = false
fullscreen_type = "Windowed"
borderless = false
transparent = false
min_width = 0
min_height = 0
max_width = 0
max_height = 0
resizable = false
visible = true
resize_on_scale_factor_change = false

[window_setup]
title = "An easy, good game"
samples = "One"
vsync = true
icon = ""
srgb = true

[backend]
type = 'All'
